### ISSUE TITLE
Resource pack not available

### ISSUE THREAD

**Issue by NhanAZ** [Endermanbugzjfc/PacketLoggerGophertunnel#23]
The server does not require downloading the resource pack

**Comment by Endermanbugzjfc** [comment]
> The server does not require downloading the resource pack

Would you mind providing your resources pack so I can reproduce the problem?

**Comment by NhanAZ** [comment]
No resource packs will be downloaded when I join `zeqa.net:19132`
```toml
[Connection]
  LocalAddress = "0.0.0.0:19132"
  RemoteAddress = "zeqa.net:19132"

[PacketLogger]
  ShowPacketType = ["ActorEvent", "ActorPickRequest", "(Look at https://pkg.go.dev/github.com/sandertv/gophertunnel@v1.19.9/minecraft/protocol/packet#pkg-index)"]

  [PacketLogger.ReportHiddenPacketCountDelay]
    Receive = "5s"
    Send = "5s"

[Reload]
  ConfigAutoReload = false
```
